-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
--
vim.keymap.set("n", "<leader>z", "<cmd>ZenMode<cr>", { silent = true })
-- local conform = require("conform")
-- -- local lint = require("lint")
-- vim.keymap.set({ "n", "v" }, "<leader>mp", function()
--   conform.format({
--     lsp_fallback = true,
--     async = false,
--     timeout_ms = 500,
--   })
-- end, { desc = "Format file or range (in visual mode)" })
--
-- local lint_augroup = vim.api.nvim_create_augroup("lint", { clear = true })
--
-- vim.api.nvim_create_autocmd({ "BufEnter", "BufWritePost", "InsertLeave" }, {
--   group = lint_augroup,
--   callback = function()
--     lint.try_lint()
--   end,
-- })
-- vim.keymap.set("n", "<leader>l", function()
--   lint.try_lint()
-- end, { desc = "Trigger linting for current file" })
