-- return {
--   {
--     'zbirenbaum/copilot.lua',
--     lazy = false,
--     cmd = 'Copilot',
--     build = ':Copilot auth',
--     opts = {
--       suggestion = { enabled = true },
--       panel = { enabled = true },
--       filetypes = {
--         markdown = true,
--         help = true,
--       },
--     },
--   },
--   {
--     'zbirenbaum/copilot-cmp',
--     config = function()
--       require('copilot_cmp').setup()
--     end,
--   },
-- }
return {}
